version: '2.1'
services:
  db:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: postgres
    env_file:
      - config/docker.env
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8080:8080